version: '3.9'

services:
  gps-proxy:
    image: dockercloud/haproxy
    links:
      - gps-service
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:80
  gps-service:
    build:
      context: .
      target: gps
    environment:
      - GPS_SERVER_PORT=8081
    deploy:
      replicas: 2

  rewards-proxy:
    image: dockercloud/haproxy
    links:
      - rewards-service
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8082:80
  rewards-service:
    build:
      context: .
      target: rewards
    environment:
      - REWARDS_SERVER_PORT=8082
    deploy:
      replicas: 2

  user-service:
    build:
      context: .
      target: user
    environment:
      - GPS_SERVICE_URL=http://gps-proxy/
      - REWARDS_SERVICE_URL=http://rewards-proxy/
    links:
      - gps-proxy
      - rewards-proxy
    ports:
      - 8080:8080
