server:
  port: '${USERS_SERVER_PORT:8080}'

app:
  gps-service:
    url: '${GPS_SERVICE_URL:http://localhost:8082/}'
  reward-service:
    url: '${REWARDS_SERVICE_URL:http://localhost:8081/}'
  trip-pricer-service:
    tripPricerApiKey: "test-server-api-key"
  tracker:
    proximityDistance: 200D
